language: objective-c
osx_image: xcode9.2
script:
    - xcodebuild clean test -project coWeave.xcworkspace -scheme coWeave -destination "platform=iOS Simulator,name=iPhone 8,OS=11.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
